

export default function Home() {
  return (
    <div >
      <h1 className="text-2xl text-center my-6 font-semibold"> WELCOME TO CHUCK NORRIS JOKS</h1>
      <p className="mb-5"> WELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
      WELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKSWELCOME TO CHUCK NORRIS JOKS
       </p>

     
    </div>
  )
}


